"""Push-уведомления: отправка через Web Push Protocol.

VAPID-ключи генерируются лениво при первой отправке push, а не в config.py.
Если ключей нет в .env — они создаются однократно и сохраняются для перезапуска.
"""

import json
import os

from flask import current_app
from py_vapid import Vapid
from pywebpush import WebPushException, webpush

from app.logger import log
from app.models import PushSubscription, User
from extensions import db

# Кешируем Vapid Instance — создаётся один раз
_vapid_instance: Vapid | None = None


def _ensure_vapid_keys() -> bool:
    """Ленивая генерация VAPID-ключей, если их нет в Config.

    Сохраняет новые ключи в .env, чтобы пережить перезапуск.
    Возвращает True если ключи доступны (были или созданы).
    """
    if current_app.config.get("VAPID_PRIVATE_KEY") and current_app.config.get("VAPID_PUBLIC_KEY"):
        return True

    try:
        from base64 import urlsafe_b64encode

        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import ec

        _key = ec.generate_private_key(ec.SECP256R1())
        pub = (
            urlsafe_b64encode(
                _key.public_key().public_bytes(
                    encoding=serialization.Encoding.X962,
                    format=serialization.PublicFormat.UncompressedPoint,
                )
            )
            .rstrip(b"=")
            .decode()
        )
        priv = (
            urlsafe_b64encode(
                _key.private_bytes(
                    encoding=serialization.Encoding.DER,
                    format=serialization.PrivateFormat.PKCS8,
                    encryption_algorithm=serialization.NoEncryption(),
                )
            )
            .rstrip(b"=")
            .decode()
        )

        current_app.config["VAPID_PUBLIC_KEY"] = pub
        current_app.config["VAPID_PRIVATE_KEY"] = priv

        # Пытаемся сохранить в .env
        _basedir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        _env_path = os.path.join(_basedir, ".env")
        if os.path.isfile(_env_path):
            with open(_env_path) as _f:
                _content = _f.read()
            _lines = []
            if "VAPID_PUBLIC_KEY" not in _content:
                _lines.append(f"VAPID_PUBLIC_KEY={pub}")
            if "VAPID_PRIVATE_KEY" not in _content:
                _lines.append(f"VAPID_PRIVATE_KEY={priv}")
            if _lines:
                with open(_env_path, "a") as _f:
                    _f.write("\n# VAPID keys for Web Push (auto-generated by push.py)\n")
                    _f.write("\n".join(_lines) + "\n")
        return True
    except Exception:
        log.warning("Failed to auto-generate VAPID keys — push disabled")
        return False


def _get_vapid() -> Vapid | None:
    """Вернуть Vapid instance из приватного ключа. Генерирует ключи лениво при первом вызове."""
    global _vapid_instance
    if _vapid_instance is not None:
        return _vapid_instance

    if not _ensure_vapid_keys():
        return None

    key = current_app.config.get("VAPID_PRIVATE_KEY")
    if not key:
        return None
    try:
        _vapid_instance = Vapid.from_string(key)
        return _vapid_instance
    except Exception as e:
        log.error(f"Failed to create Vapid instance: {e}")
        return None


def get_vapid_claims():
    """VAPID claims for push subscription."""
    return current_app.config.get("VAPID_CLAIMS", {"sub": "mailto:admin@rugram.app"})


def send_push_to_user(
    user_id, title, body, url="/", tag=None, chat_id=None, notification_id=None, category=None
):
    """Отправить push-уведомление всем подпискам пользователя.

    Args:
        category: Notification subtype ('like', 'comment', 'follow', 'message', or None).
                  If set, the user's notify_on_<category> flag is checked.
    """
    user = db.session.get(User, user_id)
    if not user:
        return False
    if not user.notifications_enabled:
        log.debug(f"Push notifications disabled for user {user_id}")
        return False
    # Per-type check
    if category:
        flag_map = {
            "like": user.notify_on_like,
            "comment": user.notify_on_comment,
            "follow": user.notify_on_follow,
            "message": user.notify_on_message,
        }
        flag = flag_map.get(category, True)
        if not flag:
            log.debug(f'Push category "{category}" disabled for user {user_id}')
            return False

    subscriptions = PushSubscription.query.filter_by(user_id=user_id).all()
    if not subscriptions:
        log.debug(f"No push subscriptions for user {user_id}")
        return False

    payload = {
        "title": title,
        "body": body,
        "tag": tag or "rugram-default",
        "url": url,
        "chatId": chat_id,
        "notificationId": notification_id,
    }
    payload_bytes = json.dumps(payload).encode("utf-8")

    vapid = _get_vapid()
    if not vapid:
        log.debug(f"VAPID not configured, skipping push to user {user_id}")
        return False

    sent_any = False
    for sub in subscriptions:
        try:
            webpush(
                subscription_info={
                    "endpoint": sub.endpoint,
                    "keys": {
                        "p256dh": sub.p256dh_key,
                        "auth": sub.auth_key,
                    },
                },
                data=payload_bytes,
                vapid_private_key=vapid,
                vapid_claims=get_vapid_claims(),
                content_encoding="aes128gcm",
            )
            sent_any = True
        except WebPushException as e:
            # If subscription expired or invalid — remove it
            if e.response and e.response.status_code in (404, 410):
                log.info(f"Removing expired push subscription for user {user_id}")
                db.session.delete(sub)
                db.session.commit()
            else:
                log.warning(f"Push send failed for user {user_id}: {e}")
                log.system_event("warning", "push", f"Push send failed for user {user_id}: {e}")
        except Exception as e:
            log.error(f"Unexpected push error for user {user_id}: {e}")
            log.system_event(
                "error",
                "push",
                f"Unexpected push error for user {user_id}: {e}",
                details=str(e)[:500],
            )

    return sent_any


def send_message_push(chat_id, recipient_id, sender_username, message_preview):
    """Отправить push при новом сообщении."""
    url = "/chat"
    send_push_to_user(
        user_id=recipient_id,
        title=sender_username,
        body=message_preview[:120],
        url=url,
        tag=f"chat-{chat_id}",
        chat_id=chat_id,
        category="message",
    )


def send_notification_push(user_id, actor_id, notification_type, post_id=None):
    """Отправить push при новом уведомлении (лайк, комментарий, подписка).

    Safe to call from a background thread — creates its own app context.
    """
    from flask import Flask

    # Build app context for thread safety
    app: Flask | None = current_app._get_current_object() if current_app else None  # type: ignore[attr-defined]
    if app is None:
        log.warning("send_notification_push: no app context, skipping push")
        return

    with app.app_context():
        actor = db.session.get(User, actor_id)
        if not actor:
            return
        actor_username = actor.username

        type_labels = {
            "like": "поставил(а) лайк",
            "comment": "оставил(а) комментарий",
            "follow": "подписался(ась) на вас",
        }
        label = type_labels.get(notification_type, notification_type)
        body = f"{actor_username} {label}"
        url = "/notifications"

        send_push_to_user(
            user_id=user_id,
            title="Rugram",
            body=body,
            url=url,
            tag=f"notification-{notification_type}",
            category=notification_type,
        )
