"""add push_subscriptions table

Revision ID: 0c1b1665909a
Revises: 0001
Create Date: 2026-06-02 00:10:49.046957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1b1665909a'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('posts', 'reposts_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('reposts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('reposts', 'created_date',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('saved_posts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('saved_posts', 'created_date',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_posts', 'created_date',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('saved_posts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('reposts', 'created_date',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('reposts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('posts', 'reposts_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
