"""add notification text field

Revision ID: d14395c24bdd
Revises: ae0cd75ad702
Create Date: 2026-06-03 13:38:30.219796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14395c24bdd'
down_revision: Union[str, Sequence[str], None] = 'ae0cd75ad702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'text')
    # ### end Alembic commands ###
